### ISSUE TITLE
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ 

### ISSUE THREAD

**Issue by niraletter** [deepnight/ld41-nightclubShowdown#3]

**Comment by deepnight** [comment]
Do you have a double GPU on this device (eg. internal Intel + another GPU)? This is often the case, even on older devices. If so, you should force the second GPU when running the game (or `hl.exe`, depending on your setup)

**Comment by HerShe04** [comment]
i only have igpu (intel graphics 3000) , can you port with dx version..sadly won't be upgrading my laptop..

**Comment by deepnight** [comment]
I added a `hl.directx.hxml` file to build the DirectX version

**Comment by deepnight** [comment]
Commit: https://github.com/deepnight/ld41-nightclubShowdown/commit/3a66b8d27dad66ddb9df1609aa4a02494450cfd8

**Comment by deepnight** [comment]
Also added a pre-built directX version in `redist` folder (https://github.com/deepnight/ld41-nightclubShowdown/commit/4c4ac862d8161756bad2552bb258d2bbb0de23a6)

**Comment by deepnight** [comment]
The DirectX build is now available for download on Itch.io: https://deepnight.itch.io/nightclub-showdown

**Comment by HerShe04** [comment]
Thanks you so much for the adding the dx version! much appriciated. <3

**Comment by HerShe04** [comment]
when i try running the gameits throwing an error
![image](https://github.com/deepnight/ld41-nightclubShowdown/assets/76764458/97972fd8-9460-4146-abda-aa42f1521dc1)

I have also updated directX

**Comment by HerShe04** [comment]
![image](https://github.com/deepnight/ld41-nightclubShowdown/assets/76764458/5d43d434-7d1b-4961-bfe4-428f3702588c)

**Comment by deepnight** [comment]
Hi, this could be related to a rather old version of DirectX: which one do you have? What is your windows version?

**Comment by HerShe04** [comment]
i have directx 12 latest and windows 8 currently
